name: Release docker image
on: 
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install git
      run: sudo apt-get install git
    - name: Quay login
      uses: docker/login-action@v2.1.0
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USER }}
        password: ${{ secrets.QUAY_TOKEN }}
    - name: Build images
      run: make all

